# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Pydantic data models for the Reasoning Engine Hello World Agent."""

from typing import List, Literal, Union
from pydantic import BaseModel, Field


class AgentInput(BaseModel):
    """Input payload from a client invoking the Hello World Agent."""

    message: str = Field(
        description="The prompt or message supplied by the external client."
    )
    user_id: str = Field(description="The identifier of the user invoking the agent.")


class AgentState(BaseModel):
    """Internal state tracking during multi-step agent reasoning."""

    current_step: str = Field(
        default="initialize",
        description="The current lifecycle step of the reasoning loop.",
    )
    resolved_tool_uri: Union[str, None] = Field(
        default=None,
        description="The dynamically resolved URI of the remote MCP tool server.",
    )
    tool_output: Union[str, None] = Field(
        default=None, description="The captured output text from the tool execution."
    )


class GetCapitalToolArgs(BaseModel):
    """Arguments payload for invoking the get_capital MCP tool."""

    location: str = Field(
        description="The country argument required by the get_capital tool."
    )


class GetHostnameToolArgs(BaseModel):
    """Arguments payload for invoking the get_hostname MCP tool."""

    pass


class GetSantizedRecordToolArgs(BaseModel):
    """Arguments payload for invoking the get_santized_record MCP tool."""

    record: str = Field(
        description="The record containing sensitive user data/PII."
    )


class ToolCallParams(BaseModel):
    """JSON-RPC parameters block specifying the target tool and its arguments."""

    name: Literal["get_capital", "get_hostname", "get_santized_record"] = Field(
        description="The tool capability name to execute.",
    )
    arguments: Union[
        GetCapitalToolArgs, GetHostnameToolArgs, GetSantizedRecordToolArgs
    ] = Field(
        description="The strongly typed arguments for the tool capability."
    )


class MCPToolRequest(BaseModel):
    """JSON-RPC 2.0 Request object constructed by the agent.
    
    Used to call a remote MCP server.
    """

    jsonrpc: Literal["2.0"] = Field(
        default="2.0",
        description="The JSON-RPC protocol version, must be exactly '2.0'.",
    )
    id: str = Field(
        description="Unique identifier generated by the agent for tracking the request."
    )
    method: Literal["tools/call"] = Field(
        default="tools/call",
        description="The standard MCP method name for executing a tool.",
    )
    params: ToolCallParams = Field(
        description="Parameters specifying the requested tool and arguments."
    )


class TextContentBlock(BaseModel):
    """A single block of text returned inside an MCP tool result content list."""

    type: Literal["text"] = Field(
        default="text", description="The type literal for a text content block."
    )
    text: str = Field(description="The raw output text generated by the tool.")


class MCPToolResult(BaseModel):
    """The result object embedded inside a successful JSON-RPC MCP response."""

    content: List[TextContentBlock] = Field(
        description="Array of content blocks containing the execution results."
    )


class MCPToolResponse(BaseModel):
    """JSON-RPC 2.0 Response object returned by the remote MCP tool server."""

    jsonrpc: Literal["2.0"] = Field(
        default="2.0",
        description="The JSON-RPC protocol version, must be exactly '2.0'.",
    )
    id: str = Field(
        description="Unique identifier mapping back to the agent's request ID."
    )
    result: MCPToolResult = Field(
        description="The output result structure from the tool."
    )


class AgentOutput(BaseModel):
    """Final structured output returned by the agent to the invoking client."""

    response: str = Field(
        description="The final synthesized response addressing the client's prompt."
    )
